apiVersion: v1
kind: Secret
metadata:
  name: orders-rabbitmq
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: orders
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample
stringData:
  RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME: changeme
  RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD: changeme