apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample
stringData:
  RETAIL_CATALOG_PERSISTENCE_USER: catalog
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: changeme