name: Publish Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
      service_projects:
        description: "Nx projects to publish"
        required: false
        default: catalog

permissions:
  id-token: write
  contents: write

jobs:
  artifacts:
    uses: ./.github/workflows/artifacts.yaml
    with:
      version: ${{ inputs.version }}
      service_projects: ${{ inputs.service_projects }}
    secrets: inherit
